export const stateCodes = {
    "Andaman & Nicobar Islands": "U01",
    "Andhra Pradesh": "S01",
    "Arunachal Pradesh": "S02",
    "Assam": "S03",
    "Bihar": "S04",
    "Chandigarh": "U02",
    "Chattisgarh": "S26",
    "Dadra & Nagar Haveli and Daman & Diu": "U03",
    "Goa": "S05",
    "Gujarat": "S06",
    "Haryana": "S07",
    "Himachal Pradesh": "S08",
    "Jammu and Kashmir": "U08",
    "Jharkhand": "S27",
    "Karnataka": "S10",
    "Kerala": "S11",
    "Ladakh": "U09",
    "Lakshadweep": "U06",
    "Madhya Pradesh": "S12",
    "Maharashtra": "S13",
    "Manipur": "S14",
    "Meghalaya": "S15",
    "Mizoram": "S16",
    "Nagaland": "S17",
    "NCT OF Delhi": "U05",
    "Odisha": "S18",
    "Puducherry": "U07",
    "Punjab": "S19",
    "Rajasthan": "S20",
    "Sikkim": "S21",
    "Tamil Nadu": "S22",
    "Telangana": "S29",
    "Tripura": "S23",
    "Uttar Pradesh": "S24",
    "Uttarakhand": "S28",
    "West Bengal": "S25",
    
}